import { ChartConfig } from '../types';

/**
 * Definición declarativa del dashboard (3 reportes).
 *
 * Cada widget es un objeto JSON serializable que el componente
 * <DynamicChart /> sabe renderizar. En la Fase 2, el Asistente IA
 * generará objetos con esta misma estructura.
 */
export const dashboardWidgets: ChartConfig[] = [
  {
    id: 'libras-netas-proceso',
    type: 'bar',
    title: 'Libras Congeladas Netas por Tipo de Proceso',
    subtitle: 'Excluye FRESH TAIL (compra de materia prima) y reempaque',
    endpoint: 'libras-netas-proceso',
    xField: 'proceso',
    yField: 'libras',
    seriesNames: ['Libras Netas'],
    sort: { field: 'libras', direction: 'desc' },
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 7 },
  },
  {
    id: 'iqf-libras-hora-dia',
    type: 'table',
    title: 'Rendimientos IQF x Hora — Diario',
    subtitle: 'Rango de fechas seleccionado · promedio de libras/hora por línea IQF',
    endpoint: 'iqf-libras-hora-dia',
    xField: 'periodo',
    xLabel: 'Fecha',
    yField: 'librasPorHora',
    seriesField: 'linea',
    excludedSeriesValues: ['SAL'],
    adaptiveDateTicks: true,
    visibleDatePointsOnly: true,
    lineCurve: 'straight',
    showAllDataMarkers: true,
    weightField: 'grupos',
    altChartType: 'line',
    valueFormat: 'decimal',
    showDataLabels: true,
    gridSpan: { xs: 12, md: 6 },
  },
  {
    id: 'iqf-libras-hora-mes',
    type: 'table',
    title: 'Rendimientos IQF x Hora — Mensual',
    subtitle: 'Últimos 12 meses (independiente del filtro de fechas)',
    endpoint: 'iqf-libras-hora-mes',
    xField: 'periodo',
    xLabel: 'Mes',
    yField: 'librasPorHora',
    seriesField: 'linea',
    excludedSeriesValues: ['SAL'],
    weightField: 'grupos',
    altChartType: 'column',
    trendChartType: 'line',
    valueFormat: 'decimal',
    showDataLabels: true,
    gridSpan: { xs: 12, md: 6 },
  },
];

/**
 * Definición declarativa del reporte de pelado (libras por estilo).
 * Mismo patrón que `dashboardWidgets`: objetos ChartConfig serializables
 * que <DynamicChart /> renderiza sin lógica específica de dominio.
 */
export const peladoWidgets: ChartConfig[] = [
  {
    id: 'pelado-por-estilo-dia',
    type: 'table',
    title: 'Libras Peladas por Estilo — Diario',
    subtitle: 'Rango de fechas seleccionado',
    endpoint: 'pelado-por-estilo-dia',
    xField: 'periodo',
    xLabel: 'Fecha',
    yField: 'libras',
    seriesField: 'estilo',
    totalAggregation: 'sum',
    adaptiveDateTicks: true,
    visibleDatePointsOnly: true,
    lineCurve: 'straight',
    altChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
  {
    id: 'pelado-por-estilo-mes',
    type: 'table',
    title: 'Libras Peladas por Estilo — Mensual',
    subtitle: 'Últimos 12 meses (independiente del filtro de fechas)',
    endpoint: 'pelado-por-estilo-mes',
    xField: 'periodo',
    xLabel: 'Mes',
    yField: 'libras',
    seriesField: 'estilo',
    totalAggregation: 'sum',
    altChartType: 'column',
    trendChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
];

/* ================================================================== */
/* Módulos de proceso — mismos patrones ChartConfig que arriba        */
/* ================================================================== */

/** Recepción de camarón de finca. */
export const recepcionWidgets: ChartConfig[] = [
  {
    id: 'recepcion-por-finca',
    type: 'cards',
    title: 'Libras Recibidas por Finca',
    subtitle: 'Rango de fechas del filtro — fuente: STB_data',
    endpoint: 'recepcion-por-finca',
    xField: 'finca',
    yField: 'libras',
    sort: { field: 'libras', direction: 'desc' },
    valueFormat: 'number',
    unitLabel: 'lbs recibidas',
    showTotalCard: true,
  },
  {
    id: 'recepcion-por-finca-dia',
    type: 'table',
    title: 'Libras Recibidas por Finca — Diario',
    subtitle: 'Rango de fechas seleccionado',
    endpoint: 'recepcion-por-finca-dia',
    xField: 'periodo',
    xLabel: 'Fecha',
    yField: 'libras',
    seriesField: 'finca',
    totalAggregation: 'sum',
    adaptiveDateTicks: true,
    visibleDatePointsOnly: true,
    lineCurve: 'straight',
    altChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
  {
    id: 'recepcion-por-finca-mes',
    type: 'table',
    title: 'Libras Recibidas por Finca — Mensual',
    subtitle: 'Últimos 12 meses (independiente del filtro de fechas)',
    endpoint: 'recepcion-por-finca-mes',
    xField: 'periodo',
    xLabel: 'Mes',
    yField: 'libras',
    seriesField: 'finca',
    totalAggregation: 'sum',
    altChartType: 'column',
    trendChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
];

/** Descabezado (libras y pago a destajo). */
export const descabezadoWidgets: ChartConfig[] = [
  {
    id: 'descabezado-por-dia',
    type: 'table',
    title: 'Libras Descabezadas por Turno — Diario',
    subtitle: 'Rango de fechas seleccionado',
    endpoint: 'descabezado-por-dia',
    xField: 'periodo',
    xLabel: 'Fecha',
    yField: 'libras',
    seriesField: 'turno',
    totalAggregation: 'sum',
    adaptiveDateTicks: true,
    visibleDatePointsOnly: true,
    lineCurve: 'straight',
    altChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
  {
    id: 'descabezado-por-dia-mes',
    type: 'table',
    title: 'Libras Descabezadas por Turno — Mensual',
    subtitle: 'Últimos 12 meses (independiente del filtro de fechas)',
    endpoint: 'descabezado-por-dia-mes',
    xField: 'periodo',
    xLabel: 'Mes',
    yField: 'libras',
    seriesField: 'turno',
    totalAggregation: 'sum',
    altChartType: 'column',
    trendChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
];

/** Clasificado por talla y por máquina (responsable de mesa). */
export const clasificadoWidgets: ChartConfig[] = [
  {
    id: 'clasificado-por-maquina',
    type: 'cards',
    title: 'Libras Clasificadas por Máquina',
    subtitle: 'Responsable de mesa · rango de fechas y turno del filtro',
    endpoint: 'clasificado-por-maquina',
    xField: 'maquina',
    yField: 'libras',
    sort: { field: 'libras', direction: 'desc' },
    valueFormat: 'number',
    unitLabel: 'lbs clasificadas',
    showTotalCard: true,
  },
  {
    id: 'clasificado-por-talla',
    type: 'cards',
    title: 'Libras Clasificadas por Talla',
    subtitle: 'Rango de fechas y turno del filtro',
    endpoint: 'clasificado-por-talla',
    xField: 'talla',
    yField: 'libras',
    sort: { field: 'libras', direction: 'desc' },
    valueFormat: 'number',
    unitLabel: 'lbs clasificadas',
    showTotalCard: true,
  },
  {
    id: 'clasificado-por-talla-dia',
    type: 'table',
    title: 'Clasificado por Talla — Diario',
    subtitle: 'Rango de fechas seleccionado',
    endpoint: 'clasificado-por-talla-dia',
    xField: 'periodo',
    xLabel: 'Fecha',
    yField: 'libras',
    seriesField: 'talla',
    totalAggregation: 'sum',
    adaptiveDateTicks: true,
    visibleDatePointsOnly: true,
    lineCurve: 'straight',
    altChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
  {
    id: 'clasificado-por-talla-mes',
    type: 'table',
    title: 'Clasificado por Talla — Mensual',
    subtitle: 'Últimos 12 meses (independiente del filtro de fechas)',
    endpoint: 'clasificado-por-talla-mes',
    xField: 'periodo',
    xLabel: 'Mes',
    yField: 'libras',
    seriesField: 'talla',
    totalAggregation: 'sum',
    altChartType: 'column',
    trendChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
  {
    id: 'clasificado-por-maquina-dia',
    type: 'table',
    title: 'Clasificado por Máquina — Diario',
    subtitle: 'Responsable de mesa · rango de fechas seleccionado',
    endpoint: 'clasificado-por-maquina-dia',
    xField: 'periodo',
    xLabel: 'Fecha',
    yField: 'libras',
    seriesField: 'maquina',
    totalAggregation: 'sum',
    adaptiveDateTicks: true,
    visibleDatePointsOnly: true,
    lineCurve: 'straight',
    altChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
  {
    id: 'clasificado-por-maquina-mes',
    type: 'table',
    title: 'Clasificado por Máquina — Mensual',
    subtitle: 'Últimos 12 meses (independiente del filtro de fechas)',
    endpoint: 'clasificado-por-maquina-mes',
    xField: 'periodo',
    xLabel: 'Mes',
    yField: 'libras',
    seriesField: 'maquina',
    totalAggregation: 'sum',
    altChartType: 'column',
    trendChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
];

/** Exportaciones. */
export const exportacionesWidgets: ChartConfig[] = [
  {
    id: 'exportaciones-por-estilo',
    type: 'cards',
    title: 'Libras Exportadas por Estilo',
    subtitle: 'Rango de fechas del filtro — fuente: AV_Envios',
    endpoint: 'exportaciones-por-estilo',
    xField: 'estilo',
    yField: 'libras',
    sort: { field: 'libras', direction: 'desc' },
    valueFormat: 'number',
    unitLabel: 'lbs exportadas',
    showTotalCard: true,
  },
  {
    id: 'exportaciones-por-cliente-dia',
    type: 'table',
    title: 'Contenedores Exportados por Cliente — Diario',
    subtitle: 'Rango de fechas seleccionado',
    endpoint: 'exportaciones-por-cliente-dia',
    xField: 'periodo',
    xLabel: 'Fecha',
    yField: 'contenedores',
    seriesField: 'cliente',
    totalAggregation: 'sum',
    adaptiveDateTicks: true,
    visibleDatePointsOnly: true,
    lineCurve: 'straight',
    altChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
  {
    id: 'exportaciones-por-cliente-mes',
    type: 'table',
    title: 'Contenedores Exportados por Cliente — Mensual',
    subtitle: 'Últimos 12 meses (independiente del filtro de fechas)',
    endpoint: 'exportaciones-por-cliente-mes',
    xField: 'periodo',
    xLabel: 'Mes',
    yField: 'contenedores',
    seriesField: 'cliente',
    totalAggregation: 'sum',
    altChartType: 'column',
    trendChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 6 },
  },
];

/** Compra de materia prima (avance de órdenes + materia prima por proveedor). */
export const compraMpWidgets: ChartConfig[] = [
  {
    id: 'compra-mp-por-proveedor',
    type: 'cards',
    title: 'Materia Prima por Proveedor',
    subtitle: 'Rango de fechas del filtro — fuente: AV_MateriaPrima',
    endpoint: 'compra-mp-por-proveedor',
    xField: 'proveedor',
    yField: 'libras',
    sort: { field: 'libras', direction: 'desc' },
    valueFormat: 'number',
    unitLabel: 'lbs de materia prima',
    showTotalCard: true,
  },
  {
    id: 'compra-mp-por-proveedor-mes',
    type: 'table',
    title: 'Materia Prima por Proveedor — Mensual',
    subtitle: 'Últimos 12 meses (independiente del filtro de fechas)',
    endpoint: 'compra-mp-por-proveedor-mes',
    xField: 'periodo',
    xLabel: 'Mes',
    yField: 'libras',
    seriesField: 'proveedor',
    totalAggregation: 'sum',
    altChartType: 'column',
    trendChartType: 'line',
    valueFormat: 'number',
    gridSpan: { xs: 12, md: 12 },
  },
];
